### ISSUE TITLE
Merge changes introduced in Stockholm's gens-fork into Lunda-gens

### ISSUE THREAD

**Issue by alkc** [SMD-Bioinformatics-Lund/gens#160]
List of PRs from https://github.com/Clinical-Genomics/gens/pulls:

- [x] [https://github.com/Clinical-Genomics/gens/pull/94](https://github.com/Clinical-Genomics/gens/pull/94)
- [x] [https://github.com/Clinical-Genomics/gens/pull/93](https://github.com/Clinical-Genomics/gens/pull/93)
- [ ] [https://github.com/Clinical-Genomics/gens/pull/92](https://github.com/Clinical-Genomics/gens/pull/92)
- [x] [https://github.com/Clinical-Genomics/gens/pull/89](https://github.com/Clinical-Genomics/gens/pull/89)
- [x] [https://github.com/Clinical-Genomics/gens/pull/88](https://github.com/Clinical-Genomics/gens/pull/88)
- [x] [https://github.com/Clinical-Genomics/gens/pull/83](https://github.com/Clinical-Genomics/gens/pull/83)
- [x] [https://github.com/Clinical-Genomics/gens/pull/80](https://github.com/Clinical-Genomics/gens/pull/80)
- [x] [https://github.com/Clinical-Genomics/gens/pull/79](https://github.com/Clinical-Genomics/gens/pull/79)
- [x] [https://github.com/Clinical-Genomics/gens/pull/78](https://github.com/Clinical-Genomics/gens/pull/78)
- [x] [https://github.com/Clinical-Genomics/gens/pull/76](https://github.com/Clinical-Genomics/gens/pull/76)
- [x] [https://github.com/Clinical-Genomics/gens/pull/75](https://github.com/Clinical-Genomics/gens/pull/75)
- [x] [https://github.com/Clinical-Genomics/gens/pull/73](https://github.com/Clinical-Genomics/gens/pull/73)
- [x] [https://github.com/Clinical-Genomics/gens/pull/70](https://github.com/Clinical-Genomics/gens/pull/70)
- [x] [https://github.com/Clinical-Genomics/gens/pull/69](https://github.com/Clinical-Genomics/gens/pull/69)
- [x] [https://github.com/Clinical-Genomics/gens/pull/66](https://github.com/Clinical-Genomics/gens/pull/66)
- [x] [https://github.com/Clinical-Genomics/gens/pull/65](https://github.com/Clinical-Genomics/gens/pull/65)
- [x] [https://github.com/Clinical-Genomics/gens/pull/64](https://github.com/Clinical-Genomics/gens/pull/64)
- [x] [https://github.com/Clinical-Genomics/gens/pull/63](https://github.com/Clinical-Genomics/gens/pull/63)
- [x] [https://github.com/Clinical-Genomics/gens/pull/62](https://github.com/Clinical-Genomics/gens/pull/62)
- [x] [https://github.com/Clinical-Genomics/gens/pull/61](https://github.com/Clinical-Genomics/gens/pull/61)
- [x] [https://github.com/Clinical-Genomics/gens/pull/60](https://github.com/Clinical-Genomics/gens/pull/60)
- [x] [https://github.com/Clinical-Genomics/gens/pull/59](https://github.com/Clinical-Genomics/gens/pull/59)
- [x] [https://github.com/Clinical-Genomics/gens/pull/55](https://github.com/Clinical-Genomics/gens/pull/55)
- [x] [https://github.com/Clinical-Genomics/gens/pull/53](https://github.com/Clinical-Genomics/gens/pull/53)
- [x] [https://github.com/Clinical-Genomics/gens/pull/51](https://github.com/Clinical-Genomics/gens/pull/51)
- [x] [https://github.com/Clinical-Genomics/gens/pull/50](https://github.com/Clinical-Genomics/gens/pull/50)
- [x] [https://github.com/Clinical-Genomics/gens/pull/49](https://github.com/Clinical-Genomics/gens/pull/49)
- [x] [https://github.com/Clinical-Genomics/gens/pull/46](https://github.com/Clinical-Genomics/gens/pull/46)
- [x] [https://github.com/Clinical-Genomics/gens/pull/45](https://github.com/Clinical-Genomics/gens/pull/45)
- [x] [https://github.com/Clinical-Genomics/gens/pull/40](https://github.com/Clinical-Genomics/gens/pull/40)
- [x] [https://github.com/Clinical-Genomics/gens/pull/28](https://github.com/Clinical-Genomics/gens/pull/28)
- [x] [https://github.com/Clinical-Genomics/gens/pull/27](https://github.com/Clinical-Genomics/gens/pull/27)

For next PR:

- [x] Placeholder
- [x] [https://github.com/Clinical-Genomics/gens/pull/23](https://github.com/Clinical-Genomics/gens/pull/23)
- [x] [https://github.com/Clinical-Genomics/gens/pull/21](https://github.com/Clinical-Genomics/gens/pull/21)
- [x] [https://github.com/Clinical-Genomics/gens/pull/20](https://github.com/Clinical-Genomics/gens/pull/20)
- [x] [https://github.com/Clinical-Genomics/gens/pull/3](https://github.com/Clinical-Genomics/gens/pull/3)
- [x] [https://github.com/Clinical-Genomics/gens/pull/4](https://github.com/Clinical-Genomics/gens/pull/4)
- [x] [https://github.com/Clinical-Genomics/gens/pull/5](https://github.com/Clinical-Genomics/gens/pull/5)
- [x] [https://github.com/Clinical-Genomics/gens/pull/6](https://github.com/Clinical-Genomics/gens/pull/6)
- [x] [https://github.com/Clinical-Genomics/gens/pull/7](https://github.com/Clinical-Genomics/gens/pull/7)
- [x] [https://github.com/Clinical-Genomics/gens/pull/8](https://github.com/Clinical-Genomics/gens/pull/8)
- [x] [https://github.com/Clinical-Genomics/gens/pull/10](https://github.com/Clinical-Genomics/gens/pull/10)
- [x] [https://github.com/Clinical-Genomics/gens/pull/9](https://github.com/Clinical-Genomics/gens/pull/9)
- [x] [https://github.com/Clinical-Genomics/gens/pull/12](https://github.com/Clinical-Genomics/gens/pull/12)
- [x] [https://github.com/Clinical-Genomics/gens/pull/13](https://github.com/Clinical-Genomics/gens/pull/13)
- [x] [https://github.com/Clinical-Genomics/gens/pull/15](https://github.com/Clinical-Genomics/gens/pull/15)
- [x] [https://github.com/Clinical-Genomics/gens/pull/14](https://github.com/Clinical-Genomics/gens/pull/14)
- [x] [https://github.com/Clinical-Genomics/gens/pull/17](https://github.com/Clinical-Genomics/gens/pull/17)
- [x] [https://github.com/Clinical-Genomics/gens/pull/18](https://github.com/Clinical-Genomics/gens/pull/18)

Stockholm specific changes

- [x] [https://github.com/Clinical-Genomics/gens/pull/42](https://github.com/Clinical-Genomics/gens/pull/42)
- [x] [https://github.com/Clinical-Genomics/gens/pull/2](https://github.com/Clinical-Genomics/gens/pull/2)
- [x] [https://github.com/Clinical-Genomics/gens/pull/22](https://github.com/Clinical-Genomics/gens/pull/22)
- [x] [https://github.com/Clinical-Genomics/gens/pull/11](https://github.com/Clinical-Genomics/gens/pull/11)
- [x] [https://github.com/Clinical-Genomics/gens/pull/1](https://github.com/Clinical-Genomics/gens/pull/1)
- [x] [https://github.com/Clinical-Genomics/gens/pull/29](https://github.com/Clinical-Genomics/gens/pull/29)
- [x] [https://github.com/Clinical-Genomics/gens/pull/30](https://github.com/Clinical-Genomics/gens/pull/30)
- [x] [https://github.com/Clinical-Genomics/gens/pull/41](https://github.com/Clinical-Genomics/gens/pull/41)
- [x] [https://github.com/Clinical-Genomics/gens/pull/31](https://github.com/Clinical-Genomics/gens/pull/31)

**Comment by Jakob37** [comment]
I think we have brought over all (and will find any missing during testing I hope)
